name: apitests 

on:
  pull_request:
    branches:
      - main
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: yes
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"
      - name: Git submodules (no clue why checkout has not got them)
        run: |
          git submodule init
          git submodule update
      - name: Start Test Server
        run: docker compose up --build backend -d
      - name: Test API
        run: cd go-api && go test -v ./...
