name: "Coverage & Backend Tests"

on:
  push:
    branches: ["*"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
  schedule:
    - cron: "0 0 * * 5"

jobs:
  configure:
    name: Configure
    runs-on: ubuntu-22.04

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{github.token}} # needs other token https://github.com/styfle/cancel-workflow-action/issues/7

      - name: Checkout
        if: steps.configure.outputs.tag != null
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  build-linux:
    name: Build Linux + Code Coverage
    needs: configure
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/workflows/setup

      - name: Run Tests and Coverage
        shell: bash
        run: |
          cd backend
          mkdir -p build
          cd build
          rm -rf *
          cmake .. -DCMAKE_BUILD_TYPE=TEST -DUSE_GCOV=ON "-DCMAKE_C_COMPILER=/bin/gcc" "-DCMAKE_CXX_COMPILER=/bin/g++"
          cmake --build . -j
          make mse-coverage -j

      - uses: codecov/codecov-action@v5
        with:
          files: ./build/mse-coverage.xml
          name: codecov-umbrella # optional
